Repository LamNz79/aq-edu-verification, pull requests merged in 2025-05, with the labels that each got.

#24 50860: Prototype: Cấu trúc bộ tiêu chuẩn
  src/app/admin/po2maj8sm7/page.tsx
  src/data/menuData.ts
  src/modules-features/admin/po2maj8sm7/F_po2maj8sm7_CreateCriteria.tsx
  src/modules-features/admin/po2maj8sm7/F_po2maj8sm7_CreateRequire.tsx
  src/modules-features/admin/po2maj8sm7/F_po2maj8sm7_CreateStandard.tsx
  src/modules-features/admin/po2maj8sm7/F_po2maj8sm7_DeleteCriteria.tsx
  src/modules-features/admin/po2maj8sm7/F_po2maj8sm7_DeleteRequire.tsx
  src/modules-features/admin/po2maj8sm7/F_po2maj8sm7_DeleteStandard.tsx
  src/modules-features/admin/po2maj8sm7/F_po2maj8sm7_Read.tsx
  src/modules-features/admin/po2maj8sm7/F_po2maj8sm7_TabCriteria.tsx
  src/modules-features/admin/po2maj8sm7/F_po2maj8sm7_TabRequire.tsx
  src/modules-features/admin/po2maj8sm7/F_po2maj8sm7_TabStandard.tsx
  src/modules-features/admin/po2maj8sm7/F_po2maj8sm7_UpdateCriteria.tsx
  src/modules-features/admin/po2maj8sm7/F_po2maj8sm7_UpdateRequire.tsx
  src/modules-features/admin/po2maj8sm7/F_po2maj8sm7_UpdateStandard.tsx
Labels: reviewed

#22 50865-đạt-prototype thiết lập nhiệm vụ báo cáo định kỳ
  src/app/admin/grtzbp3rjk/page.tsx
  src/data/menuData.ts
  src/modules-features/admin/grtzbp3rjk/F_grtzbp3rjk_ContentReportCreate.tsx
  src/modules-features/admin/grtzbp3rjk/F_grtzbp3rjk_ContentReportDelete.tsx
  src/modules-features/admin/grtzbp3rjk/F_grtzbp3rjk_ContentReportRead.tsx
  src/modules-features/admin/grtzbp3rjk/F_grtzbp3rjk_ContentReportUpdate.tsx
  src/modules-features/admin/grtzbp3rjk/F_grtzbp3rjk_Read.tsx
  src/modules-features/admin/grtzbp3rjk/F_grtzbp3rjk_StandardCarryRead.tsx
Labels: approved

#21 50862: Prototype: Lộ trình chuẩn bị
  src/app/admin/vpouokrvmt/page.tsx
  src/data/menuData.ts
  src/modules-features/admin/vpouokrvmt/F_vpouokrvmt_Create.tsx
  src/modules-features/admin/vpouokrvmt/F_vpouokrvmt_Delete.tsx
  src/modules-features/admin/vpouokrvmt/F_vpouokrvmt_Read.tsx
  src/modules-features/admin/vpouokrvmt/F_vpouokrvmt_Update.tsx
Labels: reviewed

#30 50869 - Prototype: Xuất báo cáo tự đánh giá
  src/app/admin/k25w91d9v2/page.tsx
  src/data/menuData.ts
  src/modules-features/admin/k25w91d9v2/F_k25w91d9v2_PrintPDF.tsx
  src/modules-features/admin/k25w91d9v2/ReportByCriteria.tsx
  src/modules-features/admin/k25w91d9v2/ReportByType.tsx
  src/modules-features/admin/k25w91d9v2/SelfAssessmentReport.tsx
  src/modules-features/admin/k25w91d9v2/StandardReport.tsx
  src/modules-features/auth/F0Login/F0Login.tsx
Labels: not reviewed yet
